CREATE DATABASE IF NOT EXISTS appflask;
USE appflask;
CREATE TABLE IF NOT EXISTS users(
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(256) NOT NULL,
    age INT NOT NULL,
    color VARCHAR(256) NOT NULL
)
