version: "3"

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: node-app
    environment:
      - SERVER_PORT=8000
    volumes:
      - ./:/app
    ports:
      - 8000:8000