version: '3.9'

services:
  app:
    build:
      context: .
    container_name: myapp_django
    ports:
      - 8000:8000
    environment:
      - SERVER_PORT=8000
    volumes:
      - ./:/project/app
    command: python src/manage.py runserver 0.0.0.0:8000
